apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applicationmetadata.apps.company.io
  annotations:
    description: "Custom Resource Definition for tracking application metadata, lifecycle, and dependencies"
spec:
  group: apps.company.io
  names:
    kind: ApplicationMetadata
    listKind: ApplicationMetadataList
    plural: applicationmetadata
    singular: applicationmetadata
    shortNames:
      - appmd
      - appmet
    categories:
      - apps
      - metadata
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: App-ID
          type: string
          jsonPath: .spec.id
        - name: Name
          type: string
          jsonPath: .spec.name
        - name: Business-Unit
          type: string
          jsonPath: .spec.businessUnit
        - name: Environment
          type: string
          jsonPath: .spec.environment
        - name: Version
          type: string
          jsonPath: .spec.version
        - name: Status
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - id
                - name
                - businessUnit
                - environment
                - version
              properties:
                id:
                  type: string
                  pattern: "^[a-zA-Z0-9][-a-zA-Z0-9]*[a-zA-Z0-9]$"
                  minLength: 3
                  maxLength: 63
                  description: "Unique identifier for the application"
                name:
                  type: string
                  pattern: "^[a-zA-Z][-a-zA-Z0-9]*[a-zA-Z0-9]$"
                  minLength: 2
                  maxLength: 253
                  description: "Human-readable name of the application"
                businessUnit:
                  type: string
                  pattern: "^[a-zA-Z][-a-zA-Z0-9]*[a-zA-Z0-9]$"
                  minLength: 2
                  maxLength: 63
                  description: "Business unit owning the application"
                environment:
                  type: string
                  enum:
                    - development
                    - staging
                    - production
                    - dr
                    - test
                    - qa
                  description: "Deployment environment"
                version:
                  type: string
                  pattern: "^v?(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
                  description: "Application version in semantic versioning format"
                description:
                  type: string
                  maxLength: 1024
                  description: "Detailed description of the application"
                team:
                  type: object
                  properties:
                    owner:
                      type: string
                      pattern: "^[a-zA-Z][-a-zA-Z0-9.]*[a-zA-Z0-9]$"
                      description: "Team or individual owning the application"
                    email:
                      type: string
                      pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
                      description: "Contact email for the team"
                    slack:
                      type: string
                      pattern: "^#[a-zA-Z0-9_-]+$"
                      description: "Slack channel for the team"
                composition:
                  type: array
                  description: "List of components or services that make up the application"
                  items:
                    type: object
                    required:
                      - name
                      - type
                    properties:
                      name:
                        type: string
                        pattern: "^[a-zA-Z][-a-zA-Z0-9]*[a-zA-Z0-9]$"
                        description: "Name of the component"
                      type:
                        type: string
                        enum:
                          - service
                          - database
                          - cache
                          - queue
                          - frontend
                          - backend
                          - middleware
                          - storage
                        description: "Type of the component"
                      version:
                        type: string
                        description: "Version of the component"
                      repository:
                        type: string
                        pattern: "^(https?://|git@)[\\w.-]+\\.[\\w.-]+[\\w/-]+\\.git$"
                        description: "Git repository URL"
                      dependencies:
                        type: array
                        items:
                          type: string
                          pattern: "^[a-zA-Z][-a-zA-Z0-9]*[a-zA-Z0-9]$"
                        description: "List of dependent components"
                tracking:
                  type: object
                  properties:
                    jira:
                      type: string
                      pattern: "^[A-Z]+-[0-9]+$"
                      description: "JIRA project or epic ID"
                    repository:
                      type: string
                      pattern: "^(https?://|git@)[\\w.-]+\\.[\\w.-]+[\\w/-]+\\.git$"
                      description: "Main Git repository URL"
                    pipeline:
                      type: string
                      pattern: "^[a-zA-Z][-a-zA-Z0-9/]*[a-zA-Z0-9]$"
                      description: "CI/CD pipeline identifier"
                    documentation:
                      type: string
                      pattern: "^https?://[\\w.-]+\\.[\\w.-]+[\\w/-]*$"
                      description: "Documentation URL"
                tags:
                  type: array
                  items:
                    type: string
                    pattern: "^[a-zA-Z0-9][-a-zA-Z0-9_]*[a-zA-Z0-9]$"
                  maxItems: 10
                  description: "List of tags for categorization"
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - Pending
                    - Active
                    - Deprecated
                    - Retired
                  description: "Current phase of the application lifecycle"
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      type:
                        type: string
                        enum:
                          - Ready
                          - Available
                          - Healthy
                          - UpToDate
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
                          - "Unknown"
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
                lastUpdated:
                  type: string
                  format: date-time
                  description: "Timestamp of the last update"
                observedVersion:
                  type: string
                  description: "Last observed version of the application"
                observedGeneration:
                  type: integer
                  description: "Last observed generation of the resource"