apiVersion: v1
kind: Service
metadata:
  name: pet-controller-metrics
  namespace: pet-system
  labels:
    app.kubernetes.io/name: pet-controller
    app.kubernetes.io/part-of: petstore-system
    app.kubernetes.io/component: controller
spec:
  selector:
    app.kubernetes.io/name: pet-controller
    app.kubernetes.io/component: controller
  ports:
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP