apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pets.petstore.example.com
  annotations:
    description: "Custom Resource Definition for Pet resources based on Swagger Petstore OpenAPI specification"
spec:
  group: petstore.example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        description: "A pet from the pet store"
        required:
        - spec
        properties:
          spec:
            type: object
            description: "Pet specification"
            required:
            - id
            - name
            properties:
              id:
                type: integer
                format: int64
                description: "Unique identifier for the pet"
                minimum: 1
                maximum: 9223372036854775807
              name:
                type: string
                description: "Display name of the pet"
                minLength: 1
                maxLength: 255
                pattern: "^[a-zA-Z0-9\\s\\-_\\.]+$"
              tag:
                type: string
                description: "Optional tag to categorize the pet"
                maxLength: 100
                pattern: "^[a-zA-Z0-9\\s\\-_\\.]*$"
          status:
            type: object
            description: "Pet status information"
            properties:
              phase:
                type: string
                description: "Current phase of the pet resource"
                enum:
                - "Pending"
                - "Active"
                - "Inactive"
                - "Error"
                default: "Pending"
              conditions:
                type: array
                description: "Conditions represent the latest available observations of the pet's current state"
                items:
                  type: object
                  required:
                  - type
                  - status
                  properties:
                    type:
                      type: string
                      description: "Type of condition"
                    status:
                      type: string
                      description: "Status of the condition"
                      enum:
                      - "True"
                      - "False"
                      - "Unknown"
                    lastTransitionTime:
                      type: string
                      format: date-time
                      description: "Last time the condition transitioned from one status to another"
                    reason:
                      type: string
                      description: "Unique, one-word, CamelCase reason for the condition's last transition"
                    message:
                      type: string
                      description: "Human-readable message indicating details about last transition"
              observedGeneration:
                type: integer
                format: int64
                description: "The generation observed by the controller"
    additionalPrinterColumns:
    - name: Pet-ID
      type: integer
      description: "The pet's unique identifier"
      jsonPath: .spec.id
    - name: Pet-Name
      type: string
      description: "The pet's name"
      jsonPath: .spec.name
    - name: Tag
      type: string
      description: "The pet's tag"
      jsonPath: .spec.tag
    - name: Phase
      type: string
      description: "The pet's current phase"
      jsonPath: .status.phase
    - name: Age
      type: date
      description: "Time since creation"
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: pets
    singular: pet
    kind: Pet
    shortNames:
    - pet
    categories:
    - petstore
    - animals